#!/usr/bin/env bash
# Script that do redirection 301 moved permanently

sudo apt-get update
sudo apt-get -y install nginx
# set redirection
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx start
