#!/usr/bin/env bash
# Script that do show 404 page for error page non found

sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx start
