#!/usr/bin/env bash
# Script that when receiving SIGTERM
y=2
x=1
while [ $x -eq 1 ]
do
    echo To infinity and beyond
    sleep 2
    if [ $y -eq 2 ]
    then
        echo I am invincible!!!
    fi
done