#!/usr/bin/env bash
# in this scrip we create a while with an if

x=1
while [ $x -le 10 ]
do
  if [ $x == 9 ]
  then
    echo "Hi"
    x=$(( x + 1 ))
  fi
  echo "Holberton School"
  x=$(( x + 1 ))
done
