#!/usr/bin/env bash
# in this scrip we create a while with an if

x=1
while [ $x -le 10 ]
do
  if [ $x -eq 4 ]
  then
    echo "bad luck"
  elif [ $x -eq 8 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  x=$((x=x+1))
done
