#!/usr/bin/env bash
# script to display numbers from 1 to 20

x=1
while [ $x -le 20 ]
do
  case $x in
    5) echo "bad luck from China";;
    10) echo "bad luck from Japan";;
    18) echo "bad luck from Italy";;
  esac
  echo "$x"
  ((x=x+1))
done
