#!/usr/bin/env bash
# script to display a clock

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  seconds=1
  while [ $seconds -lt 60 ]
  do
    echo "$seconds"
    ((seconds=seconds+1))
  done
  ((hour=hour+1))
done
