#!/usr/bin/env bash
# This script configures an Ubuntu server resolving localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
